// npm - global command, comes with node
// npm --version

// local dependency - use it only in this particular project
// npm i <packageName>

// globa;  dependency - use it in any project
// npm install -g <packageName>
// sudo install -g <packageName> (mac)

// package.json - manifest file (stores important info about project/package)
// manual approach (create package.json in the root , create properties, etc.)
// npm init (step by step, [press eneter to skip)
// npm init -y (everythoing default)

const _ = require("lodash");
const items = [1, [2, [3, [4]]]];
const newItems = _.flattenDeep(items);
console.log(newItems);

let obj = {
  location: {
    name: "Dhaka",
    region: "",
    country: "Bangladesh",
    lat: 23.72,
    lon: 90.41,
    tz_id: "Asia/Dhaka",
    localtime_epoch: 1640887054,
    localtime: "2021-12-30 23:57",
  },
  forecast: {
    forecastday: [
      {
        date: "2021-12-29",
        date_epoch: 1640736000,
        day: {
          maxtemp_c: 29.6,
          maxtemp_f: 85.3,
          mintemp_c: 17.9,
          mintemp_f: 64.2,
          avgtemp_c: 24.0,
          avgtemp_f: 75.2,
          maxwind_mph: 14.5,
          maxwind_kph: 23.4,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 46.0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 0.0,
        },
        astro: {
          sunrise: "06:40 AM",
          sunset: "05:21 PM",
          moonrise: "01:36 AM",
          moonset: "01:23 PM",
          moon_phase: "Third Quarter",
          moon_illumination: "31",
        },
        hour: [
          {
            time_epoch: 1640714400,
            time: "2021-12-29 00:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 19,
            wind_dir: "NNE",
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 47,
            cloud: 9,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3,
          },
          {
            time_epoch: 1640718000,
            time: "2021-12-29 01:00",
            temp_c: 19.8,
            temp_f: 67.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.7,
            wind_kph: 9.2,
            wind_degree: 24,
            wind_dir: "NNE",
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 9,
            feelslike_c: 19.8,
            feelslike_f: 67.7,
            windchill_c: 19.8,
            windchill_f: 67.7,
            heatindex_c: 19.8,
            heatindex_f: 67.7,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
          },
          {
            time_epoch: 1640721600,
            time: "2021-12-29 02:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.2,
            wind_degree: 30,
            wind_dir: "NNE",
            pressure_mb: 1016.0,
            pressure_in: 29.99,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 50,
            cloud: 8,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.5,
            gust_kph: 20.2,
          },
          {
            time_epoch: 1640725200,
            time: "2021-12-29 03:00",
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 35,
            wind_dir: "NE",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 51,
            cloud: 8,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
          },
          {
            time_epoch: 1640728800,
            time: "2021-12-29 04:00",
            temp_c: 18.6,
            temp_f: 65.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 7,
            feelslike_c: 18.6,
            feelslike_f: 65.4,
            windchill_c: 18.6,
            windchill_f: 65.4,
            heatindex_c: 18.6,
            heatindex_f: 65.4,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.5,
            gust_kph: 21.7,
          },
          {
            time_epoch: 1640732400,
            time: "2021-12-29 05:00",
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 49,
            wind_dir: "NE",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 6,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 21.8,
          },
          {
            time_epoch: 1640736000,
            time: "2021-12-29 06:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 5,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 22.0,
          },
          {
            time_epoch: 1640739600,
            time: "2021-12-29 07:00",
            temp_c: 19.0,
            temp_f: 66.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.5,
            wind_kph: 12.0,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 5,
            feelslike_c: 19.0,
            feelslike_f: 66.2,
            windchill_c: 19.0,
            windchill_f: 66.2,
            heatindex_c: 20.0,
            heatindex_f: 68.0,
            dewpoint_c: 9.0,
            dewpoint_f: 48.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.8,
            gust_kph: 20.5,
          },
          {
            time_epoch: 1640743200,
            time: "2021-12-29 08:00",
            temp_c: 20.1,
            temp_f: 68.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.0,
            wind_kph: 12.8,
            wind_degree: 59,
            wind_dir: "ENE",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 50,
            cloud: 5,
            feelslike_c: 20.1,
            feelslike_f: 68.2,
            windchill_c: 20.1,
            windchill_f: 68.2,
            heatindex_c: 22.1,
            heatindex_f: 71.8,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.9,
            gust_kph: 19.1,
          },
          {
            time_epoch: 1640746800,
            time: "2021-12-29 09:00",
            temp_c: 21.2,
            temp_f: 70.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 60,
            wind_dir: "ENE",
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 4,
            feelslike_c: 21.2,
            feelslike_f: 70.2,
            windchill_c: 21.2,
            windchill_f: 70.2,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 9.8,
            dewpoint_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.0,
            gust_kph: 17.6,
          },
          {
            time_epoch: 1640750400,
            time: "2021-12-29 10:00",
            temp_c: 23.8,
            temp_f: 74.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.0,
            wind_kph: 12.8,
            wind_degree: 53,
            wind_dir: "NE",
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 5,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 23.8,
            windchill_f: 74.9,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 10.4,
            dewpoint_f: 50.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.0,
            gust_kph: 16.1,
          },
          {
            time_epoch: 1640754000,
            time: "2021-12-29 11:00",
            temp_c: 26.5,
            temp_f: 79.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.5,
            wind_kph: 12.0,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 6,
            feelslike_c: 27.0,
            feelslike_f: 80.6,
            windchill_c: 26.5,
            windchill_f: 79.6,
            heatindex_c: 27.0,
            heatindex_f: 80.6,
            dewpoint_c: 10.9,
            dewpoint_f: 51.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.0,
            gust_kph: 14.5,
          },
          {
            time_epoch: 1640757600,
            time: "2021-12-29 12:00",
            temp_c: 29.1,
            temp_f: 84.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 34,
            cloud: 6,
            feelslike_c: 28.4,
            feelslike_f: 83.1,
            windchill_c: 29.1,
            windchill_f: 84.4,
            heatindex_c: 28.4,
            heatindex_f: 83.1,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
          },
          {
            time_epoch: 1640761200,
            time: "2021-12-29 13:00",
            temp_c: 29.3,
            temp_f: 84.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 141,
            wind_dir: "SE",
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 33,
            cloud: 7,
            feelslike_c: 28.5,
            feelslike_f: 83.2,
            windchill_c: 29.3,
            windchill_f: 84.7,
            heatindex_c: 28.5,
            heatindex_f: 83.2,
            dewpoint_c: 11.2,
            dewpoint_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.6,
            gust_kph: 13.8,
          },
          {
            time_epoch: 1640764800,
            time: "2021-12-29 14:00",
            temp_c: 29.4,
            temp_f: 85.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 243,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 32,
            cloud: 8,
            feelslike_c: 28.5,
            feelslike_f: 83.4,
            windchill_c: 29.4,
            windchill_f: 85.0,
            heatindex_c: 28.5,
            heatindex_f: 83.4,
            dewpoint_c: 11.0,
            dewpoint_f: 51.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.1,
            gust_kph: 14.6,
          },
          {
            time_epoch: 1640768400,
            time: "2021-12-29 15:00",
            temp_c: 29.6,
            temp_f: 85.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 346,
            wind_dir: "NNW",
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 8,
            feelslike_c: 28.6,
            feelslike_f: 83.5,
            windchill_c: 29.6,
            windchill_f: 85.3,
            heatindex_c: 28.6,
            heatindex_f: 83.5,
            dewpoint_c: 10.7,
            dewpoint_f: 51.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.5,
          },
          {
            time_epoch: 1640772000,
            time: "2021-12-29 16:00",
            temp_c: 27.1,
            temp_f: 80.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.7,
            wind_degree: 337,
            wind_dir: "NNW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 36,
            cloud: 7,
            feelslike_c: 27.2,
            feelslike_f: 80.9,
            windchill_c: 27.1,
            windchill_f: 80.8,
            heatindex_c: 27.2,
            heatindex_f: 80.9,
            dewpoint_c: 10.4,
            dewpoint_f: 50.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.0,
            gust_kph: 20.9,
          },
          {
            time_epoch: 1640775600,
            time: "2021-12-29 17:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.3,
            wind_kph: 18.1,
            wind_degree: 328,
            wind_dir: "NNW",
            pressure_mb: 1016.0,
            pressure_in: 29.99,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 40,
            cloud: 6,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 10.0,
            dewpoint_f: 50.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.3,
            gust_kph: 26.3,
          },
          {
            time_epoch: 1640779200,
            time: "2021-12-29 18:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 5,
            feelslike_c: 24.3,
            feelslike_f: 75.7,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.7,
            gust_kph: 31.7,
          },
          {
            time_epoch: 1640782800,
            time: "2021-12-29 19:00",
            temp_c: 21.0,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.3,
            wind_kph: 21.5,
            wind_degree: 321,
            wind_dir: "NW",
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 5,
            feelslike_c: 21.0,
            feelslike_f: 69.8,
            windchill_c: 21.0,
            windchill_f: 69.8,
            heatindex_c: 22.5,
            heatindex_f: 72.4,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 20.3,
            gust_kph: 32.6,
          },
          {
            time_epoch: 1640786400,
            time: "2021-12-29 20:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.9,
            wind_kph: 22.4,
            wind_degree: 322,
            wind_dir: "NW",
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 5,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 20.9,
            gust_kph: 33.6,
          },
          {
            time_epoch: 1640790000,
            time: "2021-12-29 21:00",
            temp_c: 18.8,
            temp_f: 65.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 14.5,
            wind_kph: 23.4,
            wind_degree: 323,
            wind_dir: "NW",
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 56,
            cloud: 5,
            feelslike_c: 18.8,
            feelslike_f: 65.8,
            windchill_c: 18.8,
            windchill_f: 65.8,
            heatindex_c: 18.8,
            heatindex_f: 65.8,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.5,
            gust_kph: 34.6,
          },
          {
            time_epoch: 1640793600,
            time: "2021-12-29 22:00",
            temp_c: 18.3,
            temp_f: 65.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 334,
            wind_dir: "NNW",
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 9,
            feelslike_c: 18.3,
            feelslike_f: 65.0,
            windchill_c: 18.3,
            windchill_f: 65.0,
            heatindex_c: 18.3,
            heatindex_f: 65.0,
            dewpoint_c: 11.0,
            dewpoint_f: 51.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
          },
          {
            time_epoch: 1640797200,
            time: "2021-12-29 23:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 344,
            wind_dir: "NNW",
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 12,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 12.2,
            dewpoint_f: 54.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
          },
        ],
      },
    ],
  },
};

const { name, country } = obj.location;

const { hour } = obj.forecast.forecastday[0];
let temp_c_1,
  temp_c_2,
  temp_c_3,
  temp_c_4,
  temp_f_1,
  temp_f_2,
  temp_f_3,
  temp_f_4 = 0;

temp_c_1 = (
  (hour[0].temp_c +
    hour[1].temp_c +
    hour[2].temp_c +
    hour[3].temp_c +
    hour[4].temp_c +
    hour[5].temp_c) /
  6
).toFixed(1);

temp_c_2 = (
  (hour[6].temp_c +
    hour[7].temp_c +
    hour[8].temp_c +
    hour[9].temp_c +
    hour[10].temp_c +
    hour[11].temp_c) /
  6
).toFixed(1);

temp_c_3 = (
  (hour[12].temp_c +
    hour[13].temp_c +
    hour[14].temp_c +
    hour[15].temp_c +
    hour[16].temp_c +
    hour[17].temp_c) /
  6
).toFixed(1);

temp_c_4 = (
  (hour[18].temp_c +
    hour[19].temp_c +
    hour[20].temp_c +
    hour[21].temp_c +
    hour[22].temp_c +
    hour[23].temp_c) /
  6
).toFixed(1);

temp_f_1 = ((9 / 5) * temp_c_1 + 32).toFixed(1);
temp_f_2 = ((9 / 5) * temp_c_2 + 32).toFixed(1);
temp_f_3 = ((9 / 5) * temp_c_3 + 32).toFixed(1);
temp_f_4 = ((9 / 5) * temp_c_4 + 32).toFixed(1);

console.log("avg of temp_c_1: " + temp_c_1);
console.log("avg of temp_c_2: " + temp_c_2);
console.log("avg of temp_c_3: " + temp_c_3);
console.log("avg of temp_c_4: " + temp_c_4);

console.log("avg of temp_f_1: " + temp_f_1);
console.log("avg of temp_f_2: " + temp_f_2);
console.log("avg of temp_f_3: " + temp_f_3);
console.log("avg of temp_f_4: " + temp_f_4);

console.log(name, country);

console.log("hello 8");
